name: Publish to Hex.pm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "26.0"
        
    - name: Install Rebar3
      run: |
        curl -LO https://s3.amazonaws.com/rebar3/rebar3
        chmod +x rebar3
        sudo mv rebar3 /usr/local/bin/
        
    - name: Build package
      run: |
        rebar3 compile
        rebar3 ex_doc
        
    - name: Configure Hex API key
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
        mkdir -p ~/.config/rebar3
        echo "{hex, [{api_key, \"$HEX_API_KEY\"}]}." > ~/.config/rebar3/hex.config
        
    - name: Publish to Hex.pm
      run: |
        rebar3 hex publish --yes
