name: Erlang CI/CD

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "26.0"
        rebar3-version: "3.22.1"
    
    - name: Setup and Build
      run: |
        # Setup hex plugin
        mkdir -p ~/.config/rebar3
        echo '{plugins, [rebar3_hex]}.' > ~/.config/rebar3/rebar.config
        
        # Build
        rebar3 deps
        rebar3 compile
        rebar3 eunit
    
    - name: Publish to Hex
      run: |
        echo "Publishing to Hex.pm..."
        
        # Simple approach - just set the environment and publish
        export HEX_API_KEY="${{ secrets.HEX_API_KEY }}"
        
        # Publish with API key as environment variable
        rebar3 hex publish --yes
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
