name: Erlang CI/CD

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "26.0"
        rebar3-version: "3.22.1"
    
    - name: Setup and Build
      run: |
        # Setup hex plugin
        mkdir -p ~/.config/rebar3
        echo '{plugins, [rebar3_hex]}.' > ~/.config/rebar3/rebar.config
        
        # Build
        rebar3 deps
        rebar3 compile
        rebar3 eunit
    
    - name: Authenticate with Hex
      run: |
        # Create hex config directory
        mkdir -p ~/.hex
        
        # Write the API key to hex config
        echo "${{ secrets.HEX_API_KEY }}" > ~/.hex/hex_api_key
        
        # Alternative: authenticate using the API key directly
        rebar3 hex user auth --key "${{ secrets.HEX_API_KEY }}"
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    
    - name: Publish to Hex
      run: |
        echo "Publishing to Hex.pm..."
        rebar3 hex publish --yes
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
