name: Erlang CI, Publish & Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: '26.0'  # Versi terbaru Erlang/OTP

    - name: Install Rebar3
      run: |
        curl -LO https://s3.amazonaws.com/rebar3/rebar3
        chmod +x rebar3
        sudo mv rebar3 /usr/local/bin/

    - name: Build project
      run: |
        rebar3 compile
        rebar3 ct  # Jika ada test
        rebar3 dialyzer  # Static analysis

    - name: Run example
      run: |
        erl -pa _build/default/lib/*/ebin -noshell -eval 'example:main()' -s init stop

    - name: Archive BEAM files
      uses: actions/upload-artifact@v4
      with:
        name: erlang-modules
        path: _build/default/lib/*/ebin/*.beam

    - name: Commit compiled modules
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        mkdir -p beam_files
        cp _build/default/lib/*/ebin/*.beam beam_files/
        
        git add beam_files/
        
        if git commit -m "Auto-commit compiled BEAM files [skip ci]"; then
          git push
        else
          echo "No changes to commit."
        fi

    - name: Publish to Hex.pm
      if: github.ref == 'refs/heads/main'
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
        rebar3 hex publish --yes
