name: Erlang CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "26.0"
        
    - name: Install Rebar3
      run: |
        curl -LO https://s3.amazonaws.com/rebar3/rebar3
        chmod +x rebar3
        sudo mv rebar3 /usr/local/bin/
        
    - name: Build
      run: |
        rebar3 deps
        rebar3 compile
        
    - name: Run Tests
      run: |
        rebar3 eunit
        
    - name: Run Dialyzer
      run: |
        rebar3 dialyzer || echo "Dialyzer completed with warnings"
        
    - name: Build Docs
      if: github.ref == 'refs/heads/main'
      run: |
        rebar3 ex_doc
        
    - name: Build and generate docs
      run: |
        rebar3 compile
        rebar3 ex_doc

    - name: Package Erlang release for Hex.pm
      run: |
        mkdir -p _build/default/hex
        TARBALL=$(rebar3 hex package | awk '/creates /{print $2}')
        echo "Created $TARBALL"

    - name: Publish to Hex.pm via API
      env:
        HEX_API_KEY: ${{ secrets.GitHubIoT }}
      run: |
        curl -v \
          -H "Authorization: Bearer $HEX_API_KEY" \
          -F "tarball=@${TARBALL}" \
          https://repo.hex.pm/api/packages/githubiot/releases
