name: Erlang CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "26.0"
        rebar3-version: "3.22.1"
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          _build
          deps
        key: ${{ runner.os }}-erlang-${{ hashFiles('**/rebar.lock') }}
        restore-keys: |
          ${{ runner.os }}-erlang-
    
    - name: Build
      run: |
        rebar3 deps
        rebar3 compile
    
    - name: Run Tests
      run: |
        rebar3 eunit
    
    - name: Run Dialyzer
      run: |
        rebar3 dialyzer || echo "Dialyzer completed with warnings"
    
    - name: Build Docs
      if: github.ref == 'refs/heads/main'
      run: |
        rebar3 ex_doc

  publish:
    name: Publish to Hex.pm
    runs-on: ubuntu-latest
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'published')
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "26.0"
        rebar3-version: "3.22.1"
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          _build
          deps
        key: ${{ runner.os }}-erlang-${{ hashFiles('**/rebar.lock') }}
        restore-keys: |
          ${{ runner.os }}-erlang-
    
    - name: Install hex plugin
      run: |
        mkdir -p ~/.config/rebar3
        echo '{plugins, [rebar3_hex]}.' > ~/.config/rebar3/rebar.config
    
    - name: Install dependencies
      run: rebar3 deps
    
    - name: Compile
      run: rebar3 compile
    
    - name: Run tests before publish
      run: rebar3 eunit
    
    - name: Configure Hex authentication
      run: |
        echo "Configuring Hex authentication..."
        
        # Method 1: Set environment variable for rebar3_hex
        export HEX_API_KEY="$HEX_API_KEY"
        
        # Method 2: Create hex config with proper format
        mkdir -p ~/.config/rebar3
        cat > ~/.config/rebar3/hex_config << EOF
          {hex_config, [
              {api_key, <<"$HEX_API_KEY">>},
              {username, <<"$HEX_USERNAME">>}
          ]}.
          EOF
        
        # Method 3: Alternative config location
        mkdir -p ~/.hex
        echo "$HEX_API_KEY" > ~/.hex/hex_api_key
        chmod 600 ~/.hex/hex_api_key
        
        # Test authentication
        echo "Testing authentication..."
        rebar3 hex user whoami || echo "Direct auth test failed, will try during publish"
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        HEX_USERNAME: ${{ secrets.HEX_USERNAME }}
    
    - name: Publish to Hex.pm
      run: |
        echo "Publishing to Hex.pm..."
        
        # Set environment variables for hex
        export HEX_API_KEY="$HEX_API_KEY"
        export HEX_USERNAME="$HEX_USERNAME"
        
        # Try multiple publish methods
        echo "Attempting to publish..."
        
        # Method 1: Direct publish with env vars
        rebar3 hex publish --yes || {
          echo "Method 1 failed, trying method 2..."
          
          # Method 2: With explicit auth
          echo "$HEX_API_KEY" | rebar3 hex user auth --stdin --username "$HEX_USERNAME" || echo "Auth failed"
          rebar3 hex publish --yes
        }
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        HEX_USERNAME: ${{ secrets.HEX_USERNAME }}
