name: Erlang CI/CD

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'release' && github.event.action == 'published')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0"
          rebar3-version: "3.22.1"

      - name: Setup and Build
        run: |
          mkdir -p ~/.config/rebar3
          echo '{plugins, [rebar3_hex]}.' > ~/.config/rebar3/rebar.config

          rebar3 deps
          rebar3 compile
          rebar3 eunit

      - name: Configure Hex.pm API key
        run: |
          mkdir -p ~/.hex
          cat <<EOF > ~/.hex/hex.config
          {default, [{api_key, "${HEX_API_KEY}"}]}.
          EOF
          chmod 600 ~/.hex/hex.config
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

      - name: Publish to Hex.pm
        run: |
          echo "Publishing to Hex.pm..."
          rebar3 hex publish --yes
