name: Erlang CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "26.0"
        
    - name: Install Rebar3
      run: |
        curl -LO https://s3.amazonaws.com/rebar3/rebar3
        chmod +x rebar3
        sudo mv rebar3 /usr/local/bin/
        
    - name: Build
      run: |
        rebar3 deps
        rebar3 compile
        
    - name: Run Tests
      run: |
        rebar3 eunit
        
    - name: Run Dialyzer
      run: |
        rebar3 dialyzer || echo "Dialyzer completed with warnings"
        
    - name: Build Docs
      if: github.ref == 'refs/heads/main'
      run: |
        rebar3 ex_doc
        
    - name: Build and generate docs
      run: |
        rebar3 compile
        rebar3 ex_doc
        
    - name: Authenticate to Hex.pm
      env:
        HEX_API_KEY: ${{ secrets.GitHubIoT }}
      run: |
        # Autentikasi ke Hex.pm dengan API key
        rebar3 hex user auth "$HEX_API_KEY"

    - name: Publish package to Hex.pm
      run: rebar3 hex publish --yes


