name: Publish to Hex.pm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: "26.0"
        
    - name: Install Rebar3
      run: |
        curl -LO https://s3.amazonaws.com/rebar3/rebar3
        chmod +x rebar3
        sudo mv rebar3 /usr/local/bin/
        
    - name: Build package
      run: |
        rebar3 compile
        rebar3 ex_doc
        
    - name: Setup Hex authentication
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
        # Create both config directories
        mkdir -p ~/.config/rebar3
        mkdir -p ~/.hex
        
        # Create config files
        echo "{hex, [{api_key, \"$HEX_API_KEY\"}]}." > ~/.config/rebar3/hex.config
        echo "{\"hexpm\":{\"api_key\":\"$HEX_API_KEY\"}}" > ~/.hex/hex.config
        
        # Set correct permissions
        chmod 600 ~/.config/rebar3/hex.config
        chmod 600 ~/.hex/hex.config
        
    - name: Verify authentication
      run: |
        rebar3 hex user g4lihru
        
    - name: Publish package
      run: |
        rebar3 hex publish --yes
